server:
  port: 7030
  servlet:
    context-path: /ads-binlog-kafka

spring:
  application:
    name: eureka-client-ads-binlog-kafka
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ads_data?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    listener:
      concurrency: 4

eureka:
  client:
    service-url:
      defaultZone: http://server001:8000/eureka/

system:
  mysql:
    host: 127.0.0.1
    port: 3306
    username: root
    password: root
    binlogName: ""
    position: -1
  kafka:
    topic: ad-search-mysql-data

