# single
#spring:
#  application:
#    name: ads-eureka
#
#server:
#  port: 8000
#eureka:
#  client:
#    fetch-registry: false
#    register-with-eureka: false
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  instance:
#    hostname: localhost

# multiple eureka
---
spring:
  application:
    name: ads-eureka
  profiles: server001
server:
  port: 8000
eureka:
  instance:
    hostname: server001
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server002:8001/eureka/,http://server003:8002/eureka/

---
spring:
  application:
    name: ads-eureka
  profiles: server002
server:
  port: 8001
eureka:
  instance:
    hostname: server002
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server001:8000/eureka/,http://server003:8002/eureka/

---
spring:
  application:
    name: ads-eureka
  profiles: server003
server:
  port: 8002
eureka:
  instance:
    hostname: server003
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://server001:8000/eureka/,http://server002:8001/eureka/
